// 1857 Uprising Centers — geographic coordinates [lng, lat]
export const REVOLT_GEO_CENTERS = [
  {
    id: 'barrackpore',
    name: 'Barrackpore',
    leader: 'Mangal Pandey',
    date: '29 March 1857',
    coordinates: [88.37, 22.76] as [number, number],
    description: 'Sepoy Mangal Pandey openly rebelled at the 34th Bengal Native Infantry parade ground.',
    primaryNotes: 'Court Martial Proceedings of Mangal Pandey; National Archives of India.',
    size: 8,
    color: [230, 57, 70],
  },
  {
    id: 'meerut',
    name: 'Meerut',
    leader: 'Sepoys of 3rd Light Cavalry',
    date: '10 May 1857',
    coordinates: [77.71, 28.98] as [number, number],
    description: 'The explosive catalyst. 85 cavalrymen refused Enfield cartridges, triggering the night march to Delhi.',
    primaryNotes: 'Fort William General Orders; Meerut Divisional Despatches.',
    size: 12,
    color: [230, 57, 70],
  },
  {
    id: 'delhi',
    name: 'Delhi (Shahjahanabad)',
    leader: 'Bahadur Shah Zafar • Bakht Khan',
    date: 'May–Sept 1857',
    coordinates: [77.23, 28.64] as [number, number],
    description: 'Bahadur Shah Zafar proclaimed Shahenshah-e-Hind. Four-month siege culminated in the British assault on Kashmiri Gate.',
    primaryNotes: 'Mutiny Papers, National Archives of India; Ghalib\'s Dastanbuy.',
    size: 18,
    color: [230, 57, 70],
  },
  {
    id: 'lucknow',
    name: 'Lucknow / Awadh',
    leader: 'Begum Hazrat Mahal',
    date: 'June 1857–March 1858',
    coordinates: [80.94, 26.84] as [number, number],
    description: 'Deepest agrarian insurrection. Begum Hazrat Mahal besieged the British Residency for months.',
    primaryNotes: 'Awadh Taluqdari petitions; General Outram despatches.',
    size: 16,
    color: [230, 57, 70],
  },
  {
    id: 'kanpur',
    name: 'Kanpur (Cawnpore)',
    leader: 'Nana Saheb • Tantia Tope',
    date: 'June–Dec 1857',
    coordinates: [80.35, 26.45] as [number, number],
    description: 'Nana Saheb led a Peshwa restoration bid. Fierce confrontations at Wheeler entrenchment and Bibighar.',
    primaryNotes: 'Kanpur Collectorate Records; British Parliamentary Inquiry.',
    size: 13,
    color: [230, 57, 70],
  },
  {
    id: 'jhansi',
    name: 'Jhansi',
    leader: 'Rani Lakshmibai',
    date: 'June 1857–April 1858',
    coordinates: [78.57, 25.45] as [number, number],
    description: 'Rani Lakshmibai fortified Jhansi Fort, resisted Sir Hugh Rose, and escaped on horseback before falling at Kotah-ki-Serai.',
    primaryNotes: 'Despatches of Major-General Sir Hugh Rose.',
    size: 15,
    color: [230, 57, 70],
  },
  {
    id: 'jagdishpur',
    name: 'Jagdishpur (Bihar)',
    leader: 'Kunwar Singh',
    date: 'July 1857–April 1858',
    coordinates: [83.96, 25.56] as [number, number],
    description: 'An 80-year-old zamindar led guerrilla warfare across Shahabad and Bhojpur districts.',
    primaryNotes: 'Patna Division Official Narrative.',
    size: 10,
    color: [230, 57, 70],
  }
];
